######################################################################
# Automatically generated by qmake (2.01a) ? 4 ? 20 10:54:00 2009
######################################################################

TEMPLATE = app
TARGET = test1
DEPENDPATH += . ../control
INCLUDEPATH += . ../control

# Input
HEADERS += \
	document.h \
	document_i.h \
	qfragmentmap_p.h

SOURCES += test.cpp \
	document_i.cpp \
	document.cpp \

