######################################################################
# Automatically generated by qmake (2.01a) ? 4 ? 20 10:54:00 2009
######################################################################

TEMPLATE = app
TARGET = test1
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../control/document.h ../control/document_i.h ../control/qfragmentmap_p.h
SOURCES += test.cpp ../control/document.cpp  ../control/document_i.cpp

