######################################################################
# Automatically generated by qmake (2.01a) ? 9 ? 29 06:10:32 2008
######################################################################

TEMPLATE = app

HEADERS = control/view.h \
	control/standard/addressview.h control/standard/hexview.h

SOURCES = control/control.cpp control/document.cpp control/cursor.cpp \
	control/view.cpp \
	control/standard/addressview.cpp control/standard/hexview.cpp \
	main.cpp

# Directories
