######################################################################
# Automatically generated by qmake (2.01a) ? 9 ? 29 06:10:32 2008
######################################################################

TEMPLATE = app
HEADERS = control/view.h
SOURCES = control/control.cpp control/document.cpp control/cursor.cpp \
	control/view.cpp \
	main.cpp

# Directories
