######################################################################
# Automatically generated by qmake (2.01a) ? 2? 2 00:53:34 2010
######################################################################

QT += testlib
TEMPLATE = app
TARGET = test
DEPENDPATH += . ../
INCLUDEPATH += . ../

# Input
HEADERS += \
	document.h \
	document_i.h \
	qfragmentmap_p.h

SOURCES += \
	doctest.cpp \
	document.cpp \
	document_i.cpp


CONFIG += x86_64
